### ISSUE TITLE
[Windows]  Installer does not work

### ISSUE THREAD

**Issue by Woggolosch** [C0untFloyd/bark-gui#100]
Launching Bark UI Enhanced v0.7.4 Server
Traceback (most recent call last):
  File "C:\bark_win\bark-gui\webui.py", line 366, in <module>
    swap_audio_filename = gr.Audio(label="Input audio.wav to swap voice", source="upload", type="filepath")
  File "C:\bark_win\installer_files\env\lib\site-packages\gradio\component_meta.py", line 159, in wrapper
    return fn(self, **kwargs)
TypeError: Audio.__init__() got an unexpected keyword argument 'source'

Any know fix? Is this project abandoned? Alternatives?

Thanks in advance.

**Comment by jxggx** [comment]
```
(venv) E:\AI\bark-gui>python webui.py
smallmodels=False
enablemps=False
offloadcpu=False
forcecpu=False
autolaunch=False


Preloading Models

Loading text model from ./models\text_2.pt to cuda
Loading coarse model from ./models\coarse_2.pt to cuda
Loading fine model from ./models\fine_2.pt to cuda
Launching Bark UI Enhanced v0.7.4 Server
Traceback (most recent call last):
  File "E:\AI\bark-gui\webui.py", line 366, in <module>
    swap_audio_filename = gr.Audio(label="Input audio.wav to swap voice", source="upload", type="filepath")
  File "E:\AI\bark-gui\venv\lib\site-packages\gradio\component_meta.py", line 159, in wrapper
    return fn(self, **kwargs)
TypeError: Audio.__init__() got an unexpected keyword argument 'source'
```


I had it running by following https://github.com/C0untFloyd/bark-gui/issues/94#issuecomment-1887424402

```
pip uninstall gradio 
pip install gradio==3.50.2
```

**Comment by PowZone** [comment]
Same error. Forcing gradio 3.50.2 didn't solved it
