### ISSUE TITLE
TypeError: Audio.__init__() got an unexpected keyword argument 'source'

### ISSUE THREAD

**Issue by web2299** [C0untFloyd/bark-gui#102]
Loading text model from ./models\text_2.pt to cuda
Loading coarse model from ./models\coarse_2.pt to cuda
Loading fine model from ./models\fine_2.pt to cuda
Launching Bark UI Enhanced v0.7.4 Server
Traceback (most recent call last):
  File "C:\Bark\bark_win\bark-gui\webui.py", line 366, in <module>
    swap_audio_filename = gr.Audio(label="Input audio.wav to swap voice", source="upload", type="filepath")
  File "C:\Bark\bark_win\installer_files\env\lib\site-packages\gradio\component_meta.py", line 159, in wrapper
    return fn(self, **kwargs)
TypeError: Audio.__init__() got an unexpected keyword argument 'source'

**The gradio is version 3.50.2**

Someone can help me please ?

**Comment by NuarkNoir** [comment]
Uninstall gradio with and install version 3.50.2
```sh
pip uninstall gradio
pip install gradio==3.50.2
```

**Comment by inikishev** [comment]
it got renamed to sources so rename source to sources
