### ISSUE TITLE
Ran windows_run tried all the command line arguments, keep getting the same error. doesn't seem to work.

### ISSUE THREAD

**Issue by YetAnotherSiteThatNeedsMyInfo** [C0untFloyd/bark-gui#105]
Traceback (most recent call last):
  File "D:\Games\barkcpu\bark-gui-main\bark-gui-main\installer\bark-gui\webui.py", line 366, in <module>
    swap_audio_filename = gr.Audio(label="Input audio.wav to swap voice", source="upload", type="filepath")
  File "D:\Games\barkcpu\bark-gui-main\bark-gui-main\installer\installer_files\env\lib\site-packages\gradio\component_meta.py", line 163, in wrapper
    return fn(self, **kwargs)
TypeError: Audio.__init__() got an unexpected keyword argument 'source'

Done!
Press any key to continue . . .

**Comment by YetAnotherSiteThatNeedsMyInfo** [comment]
Solved my own issue by reading in more detail the Issues page. This was related to the Gradio version error many others have encountered.
