### ISSUE TITLE
Assertion Error when generating custom voice

### ISSUE THREAD

**Issue by Deadstarrr** [C0untFloyd/bark-gui#12]
I uploaded a clip of me talking for around 1 minutes and 20 seconds. I uploaded the script, then I tried to generate a clip saying "Hello, I am an AI."

It failed and I received this error message:

Generating Text (1/1) -> custom\me1:`Hello, I am an AI..`
Traceback (most recent call last):
  File "J:\bark-gui\installer\installer_files\env\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "J:\bark-gui\installer\installer_files\env\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "J:\bark-gui\installer\installer_files\env\lib\site-packages\gradio\blocks.py", line 1022, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "J:\\bark-gui\installer\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "J:\\bark-gui\installer\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "J:\\bark-gui\installer\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "J:\\bark-gui\installer\installer_files\env\lib\site-packages\gradio\helpers.py", line 588, in tracked_fn
    response = fn(*args)
  File "J:\\bark-gui\installer\bark-gui\webui.py", line 114, in generate_text_to_speech
    audio_array = generate_audio(text, selected_speaker, text_temp, waveform_temp)
  File "J:\\bark-gui\installer\bark-gui\bark\api.py", line 113, in generate_audio
    out = semantic_to_waveform(
  File "J:\\bark-gui\installer\bark-gui\bark\api.py", line 54, in semantic_to_waveform
    coarse_tokens = generate_coarse(
  File "J:\\bark-gui\installer\bark-gui\bark\generation.py", line 592, in generate_coarse
    round(x_coarse_history.shape[-1] / len(x_semantic_history), 1)
AssertionError

**Comment by seruko11** [comment]
@Deadstarrr I get the same error, it has something to do with coarse history. If you turn off quick generation and then unselect coarse history it goes away.

**Comment by C0untFloyd** [comment]
Closing this as duplicate of #11
