### ISSUE TITLE
Getting AttributeError while running StartBark.bat on Windows 11

### ISSUE THREAD

**Issue by abhishek2409** [C0untFloyd/bark-gui#24]
Traceback (most recent call last):
  File "C:\projects\bark-gui\webui.py", line 295, in <module>
    gr.Markdown(f"### [{APPTITLE}](https://github.com/C0untFloyd/bark-gui)")
  File "C:\Python39\lib\site-packages\gradio\components.py", line 5931, in __init__
    IOComponent.__init__(
  File "C:\Python39\lib\site-packages\gradio\components.py", line 215, in __init__
    else self.postprocess(initial_value)
  File "C:\Python39\lib\site-packages\gradio\components.py", line 5950, in postprocess
    return self.md.render(unindented_y)
  File "C:\Python39\lib\site-packages\markdown_it\main.py", line 267, in render
    return self.renderer.render(self.parse(src, env), self.options, env)
  File "C:\Python39\lib\site-packages\markdown_it\main.py", line 252, in parse
    self.core.process(state)
  File "C:\Python39\lib\site-packages\markdown_it\parser_core.py", line 32, in process
    rule(state)
  File "C:\Python39\lib\site-packages\markdown_it\rules_core\linkify.py", line 30, in linkify
    raise ModuleNotFoundError("Linkify enabled but not installed.")
ModuleNotFoundError: Linkify enabled but not installed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\projects\bark-gui\webui.py", line 408, in <module>
    barkgui.close()
  File "C:\Python39\lib\site-packages\gradio\blocks.py", line 1389, in __exit__
    self.config = self.get_config_file()
  File "C:\Python39\lib\site-packages\gradio\blocks.py", line 1356, in get_config_file
    props = block.get_config() if hasattr(block, "get_config") else {}
  File "C:\Python39\lib\site-packages\gradio\components.py", line 5954, in get_config
    "value": self.value,
AttributeError: 'Markdown' object has no attribute 'value'

**Comment by C0untFloyd** [comment]
Your version of gradio seems to be dependant on the linkify module. I've included this in the requirements since then but in case you don't want to upgrade a 
> pip install linkify
should fix this.
