### ISSUE TITLE
ImportError: cannot import name 'pack' from 'einops' and 2 more

### ISSUE THREAD

**Issue by FollowDaRabbit** [C0untFloyd/bark-gui#34]
Thanks @C0untFloyd for resolving the "Pytorch_seed" issue! Now encountered the following after the issue above is resolved (forgot to mention I'm running StartBark.bat on Windows 10),

Traceback (most recent call last):
File "webui.py", line 21, in
from cloning.clonevoice import clone_voice
File "C:\Users\J\bark-gui-main\cloning\clonevoice.py", line 4, in
from bark.hubert.pre_kmeans_hubert import CustomHubert
File "C:\Users\J\bark-gui-main\bark\hubert\pre_kmeans_hubert.py", line 14, in
from einops import pack, unpack
ImportError: cannot import name 'pack' from 'einops' (C:\Users\J\AppData\Local\Programs\Python\Python38\lib\site-packages\einops_init_.py)

Checked and the einops has been installed already. Thx!

**Comment by FollowDaRabbit** [comment]
@C0untFloyd I solved the 'einops' above by uninstalling and reinstalling it, then installed Microsoft C++ 14.1 tool and TensorboardX, still reached the following issue (forgot to mention I'm running StartBark.bat on Windows 10),

Traceback (most recent call last):
  File "webui.py", line 21, in <module>
    from cloning.clonevoice import clone_voice
  File "C:\Users\J\bark-gui-main\cloning\clonevoice.py", line 5, in <module>
    from bark.hubert.customtokenizer import CustomTokenizer
  File "C:\Users\J\bark-gui-main\bark\hubert\customtokenizer.py", line 155, in <module>
    def auto_train(data_path, save_path='model.pth', load_model: str | None = None, save_epochs=1, max_epochs=14):
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

Can u help to take a look pls? Thanks!

**Comment by FollowDaRabbit** [comment]
@C0untFloyd I tried using the windows_run.bat.  Now I am trying to use https://github.com/C0untFloyd/bark-gui/releases/tag/v07.1 as you suggested but it stucks at Downloading text suno/bark remote model file https://huggingface.co/suno/bark/resolve/main/text_2.pt text_2.pt to ./models. 

I tried the way as suggested by @Magenta-6 but I can't find the text_2.pt anywhere (although the first attempt it stuck at 100%).  Do you know how to solve this?  Thanks!

**Comment by Magenta-6** [comment]
@FollowDaRabbit 
Try Hugging Face
https://huggingface.co/suno/bark/tree/main 
I only downloaded coarse_2.pt, fine_2.pt and text_2.pt

**Comment by C0untFloyd** [comment]
If it already wants to download the models, it means your installation finally works!
Then just do as Magenta-6 suggested and download the models manually. To be safe you could download everything with extension .pt.

**Comment by FollowDaRabbit** [comment]
@C0untFloyd I can download the .pt manually but even I put into the models folder the 1-click installer would still be stuck at the point trying to start downloading text_2.pt and not proceeding further.

@Magenta-6 are you experiencing the same thing? Can u let me know the steps u solved the issue and the absolute path for the .pt files?  

Thanks guys!

**Comment by Magenta-6** [comment]
Suno Bark at Hugging Face has the models.
https://huggingface.co/suno/bark/tree/main
I downloaded 
text_2.pt
coarse_2.pt
fine_2.pt

**Comment by FollowDaRabbit** [comment]
@Magenta-6 Thanks! Confirmed your steps solved this issue completely!
