### ISSUE TITLE
Generated voice is weird, Error 

### ISSUE THREAD

**Issue by anacondabitch** [C0untFloyd/bark-gui#37]
here is some voile clone attempt of a person with some weird  assent 

Text prompt
Now what i like you to do [clears throat] is grab -- some paint brush [laughs] and start painting just like me

sound file
http://sndup.net/n9ty

Error:
Generating Text (1/1) -> custom\MeMyselfAndI (Seed 2155879416):`Now what i like you to do [clears throat] is grab -- some paint brush [laughs] and start painting just like me`
2023-06-16 01:28:55 | ERROR | asyncio | Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "D:\bark_win\installer_files\env\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\bark_win\installer_files\env\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
2023-06-16 01:28:55 | ERROR | asyncio | Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "D:\bark_win\installer_files\env\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\bark_win\installer_files\env\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

How it happened
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
which i didn't do  .. actually it stopped abruptly and displayed this line

**Comment by C0untFloyd** [comment]
The meta tags seem to influence the stability of the generated audio badly, please also see #39 
Of course that error doesn't help either...

**Comment by anacondabitch** [comment]
yes but why am i seeing this error ? is it a bug or something .. i only encounter this error whenever i generate voice 2nd time

**Comment by C0untFloyd** [comment]
Is this only with your own custom voice? If so, could you attach it here?

**Comment by lunar-studio** [comment]
Just installed everything and I’m receiving the same errors with the same connection being reset after every prompt. Seems to follow the mention of asyncio.
