### ISSUE TITLE
ModuleNotFoundError on Windows

### ISSUE THREAD

**Issue by ahernandezmiro** [C0untFloyd/bark-gui#45]
I just updated my version of the project (currently at 664e2d8) and when I tried to run bark I got the following error when installing requirements:

`Successfully installed bark-ui-enhanced-0.7.0
Traceback (most recent call last):
  File "C:\Users\user\dev\bark_win\bark-gui\webui.py", line 5, in <module>
    import gradio as gr
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\gradio\components.py", line 26, in <module>
    import altair as alt
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\altair\__init__.py", line 607, in <module>
    from .vegalite import *
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\altair\vegalite\__init__.py", line 2, in <module>
    from .v5 import *
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\altair\vegalite\v5\__init__.py", line 2, in <module>
    from .schema import *
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\altair\vegalite\v5\schema\__init__.py", line 2, in <module>
    from .core import *
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\altair\vegalite\v5\schema\core.py", line 4, in <module>
    from altair.utils.schemapi import SchemaBase, Undefined, _subclasses
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\altair\utils\__init__.py", line 1, in <module>
    from .core import (
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\altair\utils\core.py", line 15, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'`

I have tried installing pandas directly but pip says the dependency is already installed.

Windows 10

**Comment by C0untFloyd** [comment]
This looks like a problem with Gradio or your Python installation. Are you not using a virtual env? You could also try to reinstall gradio `pip install gradio --force-reinstall`

**Comment by ahernandezmiro** [comment]
I've been using the 1 click installer so any issue with dependencies should be related with the project's dedicated virtualenv, which I have not altered. Have tried reinstalling dependencies and it did not work. Will try to delete and reinstall everything.
