### ISSUE TITLE
Exception in ASGI application

### ISSUE THREAD

**Issue by TriVectorX** [C0untFloyd/bark-gui#60]
Hi, I'm facing an issue, not sure if there is any solution to it. After the refresh installation and executing either StartBark.bat or windows_run.bat, the WebUI opens, however in the console, it throws following error and click on "Generate" (after input text and select voice) doesn't do anything. Please help and thank you very much in advance!

Error Log:

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "E:\bark-gui\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "E:\bark-gui\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "E:\bark-gui\venv\lib\site-packages\fastapi\applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "E:\bark-gui\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "E:\bark-gui\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "E:\bark-gui\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "E:\bark-gui\venv\lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "E:\bark-gui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "E:\bark-gui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "E:\bark-gui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "E:\bark-gui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "E:\bark-gui\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "E:\bark-gui\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "E:\bark-gui\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "E:\bark-gui\venv\lib\site-packages\fastapi\routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "E:\bark-gui\venv\lib\site-packages\fastapi\routing.py", line 192, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "E:\bark-gui\venv\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "E:\bark-gui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\bark-gui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\bark-gui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\bark-gui\venv\lib\site-packages\gradio\routes.py", line 291, in api_info
    return gradio.blocks.get_api_info(config, serialize)  # type: ignore
  File "E:\bark-gui\venv\lib\site-packages\gradio\blocks.py", line 528, in get_api_info
    serializer = serializing.COMPONENT_MAPPING[type]()
KeyError: 'dataset'

**Comment by kikoferrer** [comment]
Have you found the solution for this?

**Comment by neckbear2** [comment]
Try this, but make sure to do it inside your conda environment

pip uninstall gradio
pip install gradio==3.50.2
