### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType' 

### ISSUE THREAD

**Issue by JunhaoHuang0615** [C0untFloyd/bark-gui#65]
When i run  python webui.py -autolaunch in cmd, i got this error... Could anyone help me? Thank you so much!

Traceback (most recent call last):
  File "/mnt/f/bark_gui_fork/bark-gui/webui.py", line 21, in <module>
    from cloning.clonevoice import clone_voice
  File "/mnt/f/bark_gui_fork/bark-gui/cloning/clonevoice.py", line 5, in <module>
    from bark.hubert.customtokenizer import CustomTokenizer
  File "/mnt/f/bark_gui_fork/bark-gui/bark/hubert/customtokenizer.py", line 155, in <module>
    def auto_train(data_path, save_path='model.pth', load_model: str | None = None, save_epochs=1, max_epochs=14):
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by GUUser91** [comment]
Use python 3.10.
