### ISSUE TITLE
Value Error - on linux when started webui. "python3 webui.py"

### ISSUE THREAD

**Issue by FoxyHowl** [C0untFloyd/bark-gui#82]
Error log:

~/Desktop/AI/Bark/bark-gui$ python3 webui.py
Traceback (most recent call last):
  File "/home/b/Desktop/AI/Bark/bark-gui/webui.py", line 21, in <module>
    from cloning.clonevoice import clone_voice
  File "/home/b/Desktop/AI/Bark/bark-gui/cloning/clonevoice.py", line 4, in <module>
    from bark.hubert.pre_kmeans_hubert import CustomHubert
  File "/home/b/Desktop/AI/Bark/bark-gui/bark/hubert/pre_kmeans_hubert.py", line 16, in <module>
    import fairseq
  File "/home/b/miniconda3/lib/python3.11/site-packages/fairseq/__init__.py", line 20, in <module>
    from fairseq.distributed import utils as distributed_utils
  File "/home/b/miniconda3/lib/python3.11/site-packages/fairseq/distributed/__init__.py", line 7, in <module>
    from .fully_sharded_data_parallel import (
  File "/home/b/miniconda3/lib/python3.11/site-packages/fairseq/distributed/fully_sharded_data_parallel.py", line 10, in <module>
    from fairseq.dataclass.configs import DistributedTrainingConfig
  File "/home/b/miniconda3/lib/python3.11/site-packages/fairseq/dataclass/__init__.py", line 6, in <module>
    from .configs import FairseqDataclass
  File "/home/b/miniconda3/lib/python3.11/site-packages/fairseq/dataclass/configs.py", line 1104, in <module>
    @dataclass
     ^^^^^^^^^
  File "/home/b/miniconda3/lib/python3.11/dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/home/b/miniconda3/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b/miniconda3/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b/miniconda3/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory

**Comment by AIhasArrived** [comment]
Hello @FoxyHowl , were you able to finish the installation? If yes, can you tell me what models were downloaded? I can't get them. Furthermore, would you upload them to some provider and send me link to download them please? My installation is stuck at this:
![image](https://github.com/C0untFloyd/bark-gui/assets/148225825/c5419467-5ce6-4851-863d-ad7b777cc558)
And it does not advance afterwards, nothing happens, I have been waiting for a hour or so..

**Comment by manren** [comment]
try python version python3.10
