### ISSUE TITLE
Not generating even after 15 minutes (Linux Mint + RTX 2060S) - Something wrong with my installation?

### ISSUE THREAD

**Issue by HazySkies** [C0untFloyd/bark-gui#91]
![Bark Gen Times](https://github.com/C0untFloyd/bark-gui/assets/127673667/20cf172e-dece-486a-8988-46c89c7b785b)
![Bark Terminal](https://github.com/C0untFloyd/bark-gui/assets/127673667/a0ff67ef-49d1-4c88-ac73-3a07e6d9d11e)

Linux Mint 21
python: 3.10.12
torch: 2.1.1+cu118
gradio: 3.28.3 

Having issues getting anything to generate, it appears to be hanging and the terminal provides no information or indication of progress.
All settings are default and tested with a short sentence, it still not generating any results even after 15 minutes is ridiculous.

Are there any ways to diagnose generations?
What would be the likely issues causing hanging without errors?
Are there additional dependencies that could solve and/or speed up generation?

Any information would be much appreciated.

**Comment by huangyifu** [comment]
Some newer libraries are incompatible?

**Comment by HazySkies** [comment]
Oh, are there perhaps specific versions I should be using?

**Comment by machinetown44** [comment]
Having the same issue, not being able to generate anything after updating. When trying to use a saved voice, I get this error:
```
2023-12-06 00:53:47 | ERROR | asyncio | Task exception was never retrieved
future: <Task finished name='2m578lwgbb2_3' coro=<Queue.process_events() done, defined at D:\G\bark-gui\.env\lib\site-packages\gradio\queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'fn_index': 3, 'data': [...on_hash': '2m578lwgbb2'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing>
Traceback (most recent call last):
  File "D:\G\bark-gui\.env\lib\site-packages\gradio\queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "D:\G\bark-gui\.env\lib\site-packages\gradio\queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "D:\G\bark-gui\.env\lib\site-packages\gradio\queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "D:\G\bark-gui\.env\lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'fn_index': 3, 'data': [...on_hash': '2m578lwgbb2'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
```

**Comment by neckbear2** [comment]
pip uninstall gradio
pip install gradio==3.50.2

The requirements.txt should be pinned to gradio>=3.36.0,<4.0.0

4.0 and above gives TypeError: Audio.__init__() got an unexpected keyword argument 'source'
3.35.0, 3.33.1 gives  ERROR:    Exception in ASGI application
3.28.0, which someone suggested, works but fails quietly and nothing happens when you click generate.

**Comment by vedasaxena** [comment]
> ![Bark Gen Times](https://private-user-images.githubusercontent.com/127673667/285751876-20cf172e-dece-486a-8988-46c89c7b785b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNjQxMjYsIm5iZiI6MTcxNDA2MzgyNiwicGF0aCI6Ii8xMjc2NzM2NjcvMjg1NzUxODc2LTIwY2YxNzJlLWRlY2UtNDg2YS04OTg4LTQ2Yzg5YzdiNzg1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQxNjUwMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Y2Q5OTQxZDI4NjU3NTk1OTExMDUzOTVhYzVlZDBhMTQ0MDA3MjI5NWQ2NTVkNzZlMmVlNDM5MjcwMGEwOGQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6O9PMwfW5l5h9GUMbOTuV2YjiRZsrAPbHnEporrW4Tg) ![Bark Terminal](https://private-user-images.githubusercontent.com/127673667/285752603-a0ff67ef-49d1-4c88-ac73-3a07e6d9d11e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNjQxMjYsIm5iZiI6MTcxNDA2MzgyNiwicGF0aCI6Ii8xMjc2NzM2NjcvMjg1NzUyNjAzLWEwZmY2N2VmLTQ5ZDEtNGM4OC1hYzczLTNhMDdlNmQ5ZDExZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQxNjUwMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NzJkOTBlNTAwZmIxMTFlY2E5OTMzMjU2MTZjOWExZjQxNjk0YjAyYTMzOWFmNWQzMWFlZTI3ZDBjY2QxNGFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.653d3PRp5Ky-JeA2vBJ_iPlO4ND8RvM0B_H5MEsBTAY)
> 
> Linux Mint 21 python: 3.10.12 torch: 2.1.1+cu118 gradio: 3.28.3
> 
> Having issues getting anything to generate, it appears to be hanging and the terminal provides no information or indication of progress. All settings are default and tested with a short sentence, it still not generating any results even after 15 minutes is ridiculous.
> 
> Are there any ways to diagnose generations? What would be the likely issues causing hanging without errors? Are there additional dependencies that could solve and/or speed up generation?
> 
> Any information would be much appreciated.

Hello there! Were you able to find a work around to this issue? I am running into the exact problem. Have tried a bunch of things, but it is just unresponsive! Any help would be appreciated. Thanks in advance!
