### ISSUE TITLE
ModuleNotFoundError: No module named 'gradio'

### ISSUE THREAD

**Issue by nothingness6** [C0untFloyd/bark-gui#93]
As the title says, it just shows me the error. Here is the full error messages:

Traceback (most recent call last):
  File "P:\AI_Tools\bark_win\bark-gui\webui.py", line 5, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'
Press any key to continue . . .

**Comment by lunar-studio** [comment]
`pip install -r requirements.txt
`etc. etc.

**Comment by nothingness6** [comment]
> `pip install -r requirements.txt `etc. etc.

Hi, lunar.
Thanks for reply. I works, but I encountered this error this time:

Loading text model from ./models\text_2.pt to cuda
Traceback (most recent call last):
  File "P:\AI_Tools\bark_win\bark-gui\webui.py", line 260, in <module>
    preload_models()
  File "P:\AI_Tools\bark_win\bark-gui\bark\generation.py", line 347, in preload_models
    _ = load_model(
  File "P:\AI_Tools\bark_win\bark-gui\bark\generation.py", line 304, in load_model
    model = _load_model_f(ckpt_path, device)
  File "P:\AI_Tools\bark_win\bark-gui\bark\generation.py", line 269, in _load_model
    model.to(device)
  File "P:\AI_Tools\bark_win\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1160, in to
    return self._apply(convert)
  File "P:\AI_Tools\bark_win\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "P:\AI_Tools\bark_win\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "P:\AI_Tools\bark_win\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 833, in _apply
    param_applied = fn(param)
  File "P:\AI_Tools\bark_win\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 508.00 MiB. GPU 0 has a total capacty of 6.00 GiB of which 15.00 MiB is free. Of the allocated memory 4.99 GiB is allocated by PyTorch, and 10.60 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
