### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by TheMancha** [C0untFloyd/bark-gui#94]
No matter what I do, I get this error. Any advice? Thanks

smallmodels=False
enablemps=False
offloadcpu=False
forcecpu=False
autolaunch=True

Preloading Models

Loading text model from ./models\text_2.pt to cuda
Loading coarse model from ./models\coarse_2.pt to cuda
Loading fine model from ./models\fine_2.pt to cuda
Launching Bark UI Enhanced v0.7.4 Server
Traceback (most recent call last):
  File "C:\00-AI\00-BARK\bark-gui\webui.py", line 366, in <module>
    swap_audio_filename = gr.Audio(label="Input audio.wav to swap voice", source="upload", type="filepath")
  File "C:\Users\rober\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\component_meta.py", line 157, in wrapper
    return fn(self, **kwargs)
TypeError: Audio.__init__() got an unexpected keyword argument 'source'
Presione una tecla para continuar . . .

**Comment by frepein** [comment]
Had the same problem. You must install gradio manually again. I did it by editing the windows_run.bat.
Comment Line 52 and add two lines with the uninstall and install command for gradio. Run the windows_run.bat once and then remove the changes. Now bark-gui should start.

Frome Line 52:
```
@rem call python installer.py %COMMANDLINE_ARGS%
pip uninstall gradio 
pip install gradio==3.50.2
```

**Comment by vedasaxena** [comment]
> Had the same problem. You must install gradio manually again. I did it by editing the windows_run.bat. Comment Line 52 and add two lines with the uninstall and install command for gradio. Run the windows_run.bat once and then remove the changes. Now bark-gui should start.
> 
> Frome Line 52:
> 
> ```
> @rem call python installer.py %COMMANDLINE_ARGS%
> pip uninstall gradio 
> pip install gradio==3.50.2
> ```

Thank you so much. This solution worked for me. After giving it numerous attempts via manual install and running the Installer, this is the only suggestion that successfully launched the GUI.
