### ISSUE TITLE
MacOS installation error

### ISSUE THREAD

**Issue by rowild** [C0untFloyd/bark-gui#96]
The Readme says to use the flag `--enampemps`, so after running `pip install -r requirements` I did just that and ran `python webui.py --enablemps` and got these errors:

```sh
bark-gui git:(main) python webui.py --enablemps
/Users/robertwildling/miniconda3/lib/python3.11/site-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
Traceback (most recent call last):
  File "/Users/robertwildling/Desktop/_AI/bark-gui/webui.py", line 21, in <module>
    from cloning.clonevoice import clone_voice
  File "/Users/robertwildling/Desktop/_AI/bark-gui/cloning/clonevoice.py", line 4, in <module>
    from bark.hubert.pre_kmeans_hubert import CustomHubert
  File "/Users/robertwildling/Desktop/_AI/bark-gui/bark/hubert/pre_kmeans_hubert.py", line 16, in <module>
    import fairseq
  File "/Users/robertwildling/miniconda3/lib/python3.11/site-packages/fairseq/__init__.py", line 20, in <module>
    from fairseq.distributed import utils as distributed_utils
  File "/Users/robertwildling/miniconda3/lib/python3.11/site-packages/fairseq/distributed/__init__.py", line 7, in <module>
    from .fully_sharded_data_parallel import (
  File "/Users/robertwildling/miniconda3/lib/python3.11/site-packages/fairseq/distributed/fully_sharded_data_parallel.py", line 10, in <module>
    from fairseq.dataclass.configs import DistributedTrainingConfig
  File "/Users/robertwildling/miniconda3/lib/python3.11/site-packages/fairseq/dataclass/__init__.py", line 6, in <module>
    from .configs import FairseqDataclass
  File "/Users/robertwildling/miniconda3/lib/python3.11/site-packages/fairseq/dataclass/configs.py", line 1104, in <module>
    @dataclass
     ^^^^^^^^^
  File "/Users/robertwildling/miniconda3/lib/python3.11/dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/Users/robertwildling/miniconda3/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robertwildling/miniconda3/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robertwildling/miniconda3/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory
```

Either I misunderstand the usage of `--enablemps` or there is an error somewhere else. Does anybody have a clue what is happening here?

**Comment by LFClaro** [comment]
Same issue here. Any news on this?

**Comment by LFClaro** [comment]
I was able to run it by using Python 3.10 instead of 3.11. I found this solution on issue #40 .
